version: '3.8'

services:
  app:
    image: elessandrodev/php-core:v1.0.1
    working_dir: /var/www/
    volumes:
      - .:/var/www
    command: >
      sh -c "composer install && php artisan test --coverage-clover=coverage.xml"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ci_network

  mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ci_network

networks:
  ci_network:
    driver: bridge
